### PR TITLE
WIP: starting danger experiments

### PR DESCRIPTION
**Pull request by vhbit**
Have to have it is as a pull-request to make danger working on Travis

### CODE REVIEW

**Comment by vhbit** [comment]
@ornithocoder so what do we do with this?

**Comment by ornithocoder** [comment]
@vhbit oh, yeah, definitely. I just want to take a look on the swiftlint rules first. I'm short in time this week :-(

**Comment by vhbit** [comment]
@ornithocoder what I suggest to do is to see which rules in this exact PR you don't like - so they can be adjusted in this PR. And later configuration will be updated incrementally on cases `swiftlint` suggests something you don't like

**Comment by ornithocoder** [comment]
I've pushed to a branch called `swiftlint` the settings I like and code changes to make it work with those settings. I'm thinking of merging the branch into master later tonight or tomorrow.

Unfortunately swiftlint doesn't have a rule for how long methods should be broken (multiline). I will take a look later on how to implement custom swiftlint rules.

**Comment by ornithocoder** [comment]
My SwiftLint rule was merged into SwiftLint's master. It should be available on next SwiftLint version.

**Comment by ornithocoder** [comment]
Closing this PR. The project won't use Danger for now. Thanks.

**Pull request closed without merging**
